CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(80) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('user','admin') NOT NULL DEFAULT 'user',
 blocked TINYINT NOT NULL DEFAULT 0,
 quota_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
 session_version INT NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS folders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 parent_id BIGINT UNSIGNED NULL,
 name VARCHAR(180) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(parent_id) REFERENCES folders(id) ON DELETE RESTRICT,
 INDEX(user_id,parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS files (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 folder_id BIGINT UNSIGNED NULL,
 name VARCHAR(240) NOT NULL,
 mime VARCHAR(150) NOT NULL DEFAULT 'application/octet-stream',
 size BIGINT UNSIGNED NOT NULL,
 status ENUM('uploading','ready','trash') NOT NULL DEFAULT 'uploading',
 favorite TINYINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(folder_id) REFERENCES folders(id) ON DELETE RESTRICT,
 INDEX(user_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS chunks (
 file_id BIGINT UNSIGNED NOT NULL,
 part INT UNSIGNED NOT NULL,
 remote_id VARCHAR(255) NOT NULL,
 message_id BIGINT NOT NULL,
 size INT UNSIGNED NOT NULL,
 PRIMARY KEY(file_id,part),
 FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS login_attempts (
 bucket CHAR(64) PRIMARY KEY,
 attempts INT NOT NULL DEFAULT 0,
 started_at BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS settings (
 name VARCHAR(80) PRIMARY KEY,
 value TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
